### ISSUE TITLE
Game analysis not trustworthy due to low-quality cloud evals

### ISSUE THREAD

**Issue by fcurts** [lichess-org/mobile#1623]
When I analyze my games, I constantly hit cloud evals that either have very low depth (often <20, as low as 14) or greatly differ from SF 16/17 eval at similar depth (up to more than 100%, presumably due to cloud eval using old SF version). For these reasons, it’s impossible to do trustworthy game analysis in the app.

Potential solutions:
1. Allow to request local eval even if cloud eval exists. I believe this is what the web app does. However, it’s very inconvenient to manually request local eval each time because there are so many low-depth cloud evals and even high-depth cloud evals can’t be trusted.
2. Add setting to ignore cloud evals below a configurable depth. This would be my favorite solution.
3. Improve cloud evals to use a single known SF version and depth >= 35 (discard all other cloud evals).

**Comment by dstark1993** [comment]
Are you talking about computer analysis where it goes over the whole game or just a single move stockfish eval?
- Single move eval can go deep (click setting and add eval time and/or more cpu cores), SF 16 is shown.
- For computer analysis, I actually dont know you have control over depth etc. If not, I guess its what they decided is good enough considering there are thousand of requests so some compromise must be had.

**Comment by fcurts** [comment]
@dstark1993 I’m talking about single move eval. If a cloud eval exists (even as low as depth 14), the local eval never kicks in. There isn’t currently a setting to change this.

**Comment by dstark1993** [comment]
Oh I see what you are saying. Though the only time I get cloud eval is for very early positions where the depth is already above 30.
Can you share a position where this happens for you? (cloud eval lower than depth ~20)

**Comment by fcurts** [comment]
They’re everywhere:

r1bq1rk1/1pp2ppp/3p1n2/8/p2QP3/P1N5/1PP2PPP/2KR1B1R b - - 0 13

**Comment by veloce** [comment]
I like option `#2` because it is easy to implement.

**Comment by dstark1993** [comment]
> They’re everywhere:
> 
> r1bq1rk1/1pp2ppp/3p1n2/8/p2QP3/P1N5/1PP2PPP/2KR1B1R b - - 0 13

I see, yes this is somewhat frustrating if you want a deeper analysis but you cant.

Previous app had an + sign in which you could request deeper analysis even if cloud analysis was provided. Wonder if it will be easier to implement (in this app the analysis is set by the time and cores you are willing to use).

**Comment by veloce** [comment]
> They’re everywhere:
> 
> r1bq1rk1/1pp2ppp/3p1n2/8/p2QP3/P1N5/1PP2PPP/2KR1B1R b - - 0 13

Tried this position in lichess analysis, didn't get a cloud evaluation.

**Comment by veloce** [comment]
Fixed now with last release. Cloud evals are ignored for all plies before 15.

**Comment by fcurts** [comment]
This slightly improves the situation but doesn’t solve it:

1. I’m still getting cloud evals with low depth.
2. Cloud evals and local evals with different depths and SF versions aren’t comparable, making serious analysis impossible.

Cloud evals shouldn’t replace local evals, only augment them (as done in ChessBase). At a minimum, there should be a way to turn them off.

**Comment by veloce** [comment]
I'm reluctant to put new settings but I agree there should be a way to disable cloud evals for user who don't want them, so I'll think about it.

**Comment by veloce** [comment]
There is already a way to disable cloud eval, by the way: setting engine search time to "Infinity".

**Comment by fcurts** [comment]
> There is already a way to disable cloud eval, by the way: setting engine search time to "Infinity".

I already had it set to infinity, but I still get cloud evals.

**Comment by fcurts** [comment]
Unfortunately, this isn’t working as advertised in the PR. Even though I have analysis time set to infinite, I keep getting cloud evals with extremely low depth (e.g., 13). To get a local eval, I need to click the engine icon followed by “go deeper” in every position, which is a poor user experience. Tested with 0.15.7.

**Comment by ijm8710** [comment]
Have you got the go deeper button to do anything? I was curious if I was doing something wrong before submitting a bug report but I don't see it do anything on iOS and it almost feels like it doesn't click the button when I touch it

**Comment by fcurts** [comment]
@ijm8710 The “go deeper” button seems to work fine on my iPad. But I really don’t want to be forced to click it all the time.

**Comment by veloce** [comment]
Cannot reproduce seeing cloud evals when setting engine search time to infinity. But I indeed found a bug which prevented the analysis to work with the infinity settings, and I'm fixing it.

**Comment by ijm8710** [comment]
Anything relating to iOS go deeper button not working or should I file another ticket for that specifically?

**Comment by veloce** [comment]
It's working for me.

**Comment by fcurts** [comment]
Here you can see that setting search time to infinity doesn’t help. Depth information (14 vs. 6) is also confusing. Only goes deeper once I click “go deeper”.

![Image](https://github.com/user-attachments/assets/09b52d5f-eda1-4e94-8d8b-afe65456b8ed)
![Image](https://github.com/user-attachments/assets/cdd9db91-10d4-428f-ba6e-05896139ec8e)

**Comment by veloce** [comment]
That is the above mentioned bug which is now fixed.
