### ISSUE TITLE
iOS app shows permanent notification badge on icon since last update

### ISSUE THREAD

**Issue by KervyN** [lichess-org/mobile#2406]
### What is the problem?

iOS version: 26.1 
App Version: 0.18.2

The app shows a permanent notification on the icon since the last update. 

There are no notifications on the website and even logout, reinstalling and restarting the phone did not help. 

As soon as the app is installed there is the (1). 

The old app doesn't have this problem. 

### Steps to reproduce the bug

1. Install the app
2. allow notifications 

### App version

0.18.2

### Device Info

iOS 26.1

**Comment by milleranalytics** [comment]
I have this same issue.  Persistent stuck badge icon that does not disappear even when logged out of my account, so it is not due to a notification on my account, but rather some bug with the app itself on iOS.  Of note, I also have the iPadOS variant installed and my iPad does not exhibit this issue.

**Comment by rchoucroun** [comment]
This one is really annoying. I see a badge and think I have moves to play.

**Comment by tom-anders** [comment]
@KervyN @milleranalytics @rchoucroun a server-side fix has been deployed today that potentially could fix these issues. Can you test and report back? Thanks!

**Comment by rchoucroun** [comment]
Yeah. I think that fixed it. Thanks.

**Comment by rchoucroun** [comment]
Actually, maybe I spoke too soon. It is a bit flaky. There is a delay or something. A notification badge is still showing but no moves to make. 

It was working.

**Comment by KervyN** [comment]
@tom-anders 

Nope, still there. What I tried:

* Log off / Log in
* Remove App / Install App
* Restart Phone

The notification badge show up right after the installation, without being logged in.

**Comment by milleranalytics** [comment]
@tom-anders, similar experience as @KervyN, but with a new wrinkle.

On my iPhone on iOS 26.1:

1. Log out - badge remains despite nobody being logged in
2. Remove App, Restart iPhone, Reinstall App (not logged in yet) - badge reappears right away after giving permissions to send notifications.
3. Log in - Badge disappears!
4. Close app - Badge temporarily appears for about 1 second and then disappears.

So something is still not working as I'd expect it, but at least (for now) the badge appears to be behaving. The temporary appearance of it when closing the app and the fact that it showed up after a fresh install without being logged in makes me think there is still a bug hiding in here somewhere. 

I'll see if I start also now getting notifications when it is my turn in a correspondence game.  That was also broken (I assume tied to this bug).  I also have the app on my iPad and the iPad was not getting notifications either, although did not have the issue with the stuck badge.

Update:
I received a notification (app badge) when it was my turn in a correspondence game.  After making my turn, the badge is now stuck again.

**Comment by babyerle** [comment]
I updated the iOS app for the first time in weeks today. Now my notification badge is stuck at 1.

**Comment by babyerle** [comment]
Oh wait now it’s gone. Hurray!

**Comment by KervyN** [comment]
> Oh wait now it’s gone. Hurray!

@babyerle Are your notifications enabled? Which iOS and app version do you have?

**Comment by babyerle** [comment]
I have iOS 18.6.2 and the new mobile app version v. 0.18.2.

After I posted that it was working the problem of a stuck badge reappeared. I use two Lichess apps on my phone. One is the one already mentioned. The other is a "shortcut" to the full Lichess mobile website.

The badge gets stuck on the mobile app. It doesn't on the shortcut app. However, the shortcut sends me double notifications every time there is a correspondence move.

The new mobile app sends notifications but they have no sound. The badge annoyed me so much that I just turned off notifications for that app.

**Comment by babyerle** [comment]
Another thing that might be relevant is that I don't have the badge problem on the mobile app on iPad.

app 0.18.2
iPadOS 18.7.3

**Comment by rchoucroun** [comment]
For me, at the moment, I have a badge with just a "1" whether or not I have a move to make or not. 

I have all alerts enabled (lock screen, notification centre, banners) in addition to banners. 

I also have the old app installed which has the same notification settings enabled. But, it displaying the badge correctly. 

App Version: v0.18.2
iOS 26.1 (23B85)

**Comment by babyerle** [comment]
Huzzah for v. 0.19.0!

notifications and badge working correctly!

**Comment by tom-anders** [comment]
Fixed has been confirmed in 0.19.0 prerelease by multiple devices/users, so I think we can close this issue as well

**Comment by tom-anders** [comment]
Looks like there are still issues on 0.19.0 with the badge (but notifications at least seem to arrive again now), so I'm reopening this issue

**Comment by KervyN** [comment]
@tom-anders 

Tesflight version 0.19.2 seems to have solved it. At least the notification bubble is gone. 

As soon as my correspondence game makes a move, I can tell of notifications are working correctly. 

Edit: It is working as expected. For me, the issue is now fixed.

**Comment by tom-anders** [comment]
With 0.19.3 the badge is fixed on my iOS device as well. If anyone still has issues, feel free to comment here, but I'm closing this for now. (For anyone who is not on TestFlight yet: https://testflight.apple.com/join/WEurB7MT)
