### ISSUE TITLE
Notifications not working on iOS

### ISSUE THREAD

**Issue by chewie01100** [lichess-org/mobile#2418]
### What is the problem?

A notification icon showing one unacknowledged notification is always on for the lichess widget, even if I have more than one notification or none to deal with. Moreover, I am not getting notifications otherwise (for example, in my correspondence games, I am not getting notifications about opponents' moves). 

### Steps to reproduce the bug

1. Look at the widget on iOS. 
2. Notice that the red notification marker does not change: does not increase or decrease from one.

### App version

0.18.2

### Device Info

iPhone 13

**Comment by Prezesssso** [comment]
yes. exactly the same for me - iphone 15pro

**Comment by KervyN** [comment]
This is the same as this, right? #2406

**Comment by Prezesssso** [comment]
yesOn 4 Dec 2025, at 13:04, Boris ***@***.***> wrote:﻿KervyN left a comment (lichess-org/mobile#2418)
This is the same as this, right? #2406

**Comment by thomastay** [comment]
Having the same issue. I have two correspondence games on, but when the opponent moves, I do not receive a notification.

**Comment by tom-anders** [comment]
@chewie01100 @thomastay @Prezesssso a server-side fix has been deployed today that potentially could fix these issues. Can you test and report back? Thanks!

**Comment by Prezesssso** [comment]
not resolved am afraid - removed the app and re-installed - bad notificwtion reappeared straight awayOn 12 Dec 2025, at 07:46, Tom Praschan ***@***.***> wrote:﻿tom-anders left a comment (lichess-org/mobile#2418)
@chewie01100 @thomastay @Prezesssso a server-side fix has been deployed today that potentially could fix these issues. Can you test and report back? Thanks!

**Comment by chewie01100** [comment]
> [@chewie01100](https://github.com/chewie01100) [@thomastay](https://github.com/thomastay) [@Prezesssso](https://github.com/Prezesssso) a server-side fix has been deployed today that potentially could fix these issues. Can you test and report back? Thanks!

Unfortunately, it is still broken.

**Comment by babyerle** [comment]
I confirm also that my notification is stuck at 1 and that I am not receiving notifications from my correspondence games. I commented elsewhere on the badge issue but just noticed today that the notifications I was getting were coming from my Lichess home screen bookmark rather than from the mobile app.

iOS 26.2
Lichess mobile app 0.18.2

**Comment by babyerle** [comment]
Notifications and badge count are working now. iPadOS 18.7.3 and Lichess TestFlight app 0.19.0.

Also confirmed working on iOS 26.2 app TestFlight 0.19.0

Great job you guys!

**Comment by tom-anders** [comment]
Awesome! I also confirmed the fix on my own ios device with 0.19.0, what a nice Christmas gift.

**Comment by KervyN** [comment]
@tom-anders do I need to do something special?

I've removed the app store version and installed 0.19.0 from test flight, but the issue is still there. 

iOS is also on 26.2

**Comment by tom-anders** [comment]
> [@tom-anders](https://github.com/tom-anders) do I need to do something special?
> 
> I've removed the app store version and installed 0.19.0 from test flight, but the issue is still there.
> 
> iOS is also on 26.2

So in theory it should be enough to open the app, accept the popup to allow notifications and then log into your account.

*However*, while investigating this bug I actually found another issue where notifications would not be activated after being logged in, and requiring another fresh start of the app instead.

So can you try to kill the app, and then open it again? Hopefully that should do the trick.

**Comment by chewie01100** [comment]
> > [@tom-anders](https://github.com/tom-anders) do I need to do something special?
> > I've removed the app store version and installed 0.19.0 from test flight, but the issue is still there.
> > iOS is also on 26.2
> 
> So in theory it should be enough to open the app, accept the popup to allow notifications and then log into your account.
> 
> _However_, while investigating this bug I actually found another issue where notifications would not be activated after being logged in, and requiring another fresh start of the app instead.
> 
> So can you try to kill the app, and then open it again? Hopefully that should do the trick.

Unfortunately, the issue is still present for me, even after these steps.

**Comment by tom-anders** [comment]
> > > [@tom-anders](https://github.com/tom-anders) do I need to do something special?
> > > I've removed the app store version and installed 0.19.0 from test flight, but the issue is still there.
> > > iOS is also on 26.2
> > 
> > 
> > So in theory it should be enough to open the app, accept the popup to allow notifications and then log into your account.
> > _However_, while investigating this bug I actually found another issue where notifications would not be activated after being logged in, and requiring another fresh start of the app instead.
> > So can you try to kill the app, and then open it again? Hopefully that should do the trick.
> 
> Unfortunately, the issue is still present for me, even after these steps.

Which issue exactly? Notifications not arriving, or the badge not updating, or both?

Also, do you have only one device, or multiple devices with the new app?

**Comment by chewie01100** [comment]
Both issues: sorry for not being clear--I just think of them as the same issue!

I only have one device: iPhone 13 running iOS 18.7.1.

**Comment by tom-anders** [comment]
No problem! Some more fixes have been pushed, hopefully the next testflight release will fix it for you as well

**Comment by chewie01100** [comment]
> No problem! Some more fixes have been pushed, hopefully the next testflight release will fix it for you as well

Great. I must admit I am a bit confused about the difference between a testflight release and app store availability. These are different?

**Comment by KervyN** [comment]
> > [@tom-anders](https://github.com/tom-anders) do I need to do something special?
> > 
> > I've removed the app store version and installed 0.19.0 from test flight, but the issue is still there.
> > 
> > iOS is also on 26.2
> 
> So in theory it should be enough to open the app, accept the popup to allow notifications and then log into your account.
> 
> *However*, while investigating this bug I actually found another issue where notifications would not be activated after being logged in, and requiring another fresh start of the app instead.
> 
> So can you try to kill the app, and then open it again? Hopefully that should do the trick. 

Tried that, didn't work. 

I have a constant 1 at the app icon. 

Also tried to log out and restart the phone.

**Comment by tom-anders** [comment]
> > No problem! Some more fixes have been pushed, hopefully the next testflight release will fix it for you as well
> 
> Great. I must admit I am a bit confused about the difference between a testflight release and app store availability. These are different?

They are the same code/versions, but Testflight gets new versions before they are released on the app store, it's like a beta test

**Comment by tom-anders** [comment]
Interestingly, notifications now work for me on 0.19.0, but there's still the issue if the badge always showing a "1". It looks like these are separate issues after all.

So I will keep this issue closed but reopen #2406

**Comment by Prezesssso** [comment]
still not resolved even in most recent update ?!?On 24 Dec 2025, at 11:52, Tom Praschan ***@***.***> wrote:﻿tom-anders left a comment (lichess-org/mobile#2418)
Interestingly, notifications now work for me on 0.19.0, but there's still the issue if the badge always showing a "1". It looks like these are separate issues after all.
So I will keep this issue closed but reopen #2406

**Comment by tom-anders** [comment]
With 0.19.4, I'm not seeing either issue anymore
