### ISSUE TITLE
Correct move in puzzle gets reverted as if it wasn't the correct move

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#292]
Today I encountered a weird bug - please refer to the following screen recording:

https://github.com/lichess-org/mobile/assets/118524250/85d17cf3-ba03-4533-875d-42b5b40bf6e2

Expected behavior: the puzzle continues after the correct move. 

What happened instead: the moved rook was put on its original square just like if it wasn't the correct move. Look at the green check mark and the "Best move - continue" message on the top of the sceen (it was the best move). 

Steps to reproduce the bug: I'm not sure. This is the first time I've ever seen this bug. It seems like it happens more often if the player drag-and-drops the pieces instead of tapping them. Relatively fast movement makes it happen more frequently as well. 

After replaying the puzzle several times, Rexc2 was accepted and I was able to finish the puzzle.

**Comment by veloce** [comment]
Please provide a link to the puzzle. I need to be able to reproduce to understand what's going on.

**Comment by NewSupKaizo55** [comment]
I did some experiments related to the bug.

- I was able to reproduce it on seemingly any puzzle
- All pieces are affected, not just rooks
- Tapping triggers it too, not just drag-and-drop
- It seems to be related to fast movement of the pieces

I hope this helps at least a little bit.

**Comment by veloce** [comment]
> I was logged out when I played that puzzle. Is there any way I could trace that puzzle back based on the position (like with the api maybe)?
> 
> Edit: tried to put it into opening explorer without fiters and couldn't find it.

you could try the puzzle history page on the website and find the position

**Comment by veloce** [comment]
I think this bug is now fixed because premoves are disabled for puzzles (from version 0.4.2).

Please let me know if you ever reproduce again.

**Comment by NewSupKaizo55** [comment]
New version, this was recorded like a minute ago. I can still reproduce it effortlessly. I just have to play the first move really fast. 

https://github.com/lichess-org/mobile/assets/118524250/22f5dea9-8979-4512-b1fc-72c54b33719c
