### ISSUE TITLE
Move notification action does not go to current state of game

### ISSUE THREAD

**Issue by xdemiansmithx** [lichess-org/mobile#640]
### What is the problem?

When your opponent makes a move in a correspondence game if you were in the game still, clicking the app / opening the app does not go to the current state of the game but to the state before the move (i.e. the state you left the game in the background). 

### Steps to reproduce the bug

1. Join correspondence game
2.  Make a couple of moves
3.  After your last move, minimise the app (i.e. put to background)
4. Have opponent make a move
5. Observe badge indicating it is your turn
6. Click / open the app 
7. State dos not update

### What did you expect to happen?

State of game should be updated

### What happened instead?

The game went back to the last "seen" state, so I had to go back > back > into the game

### Device Info

iPhone 12 mini

### Operating System Version

iOS 17.4,1

**Comment by ijm8710** [comment]
Agree with this post and have shared the same. 

In addition to it not opening from right spot when clicking alert: 

- recieve alert. But this time, instead of opening the alert, instead simply open the app. The feed should be automatically registering that it is now your turn, but it is failing to do so 
- open alert (the game will actually register it is your turn this time), but instead of playing a move, backswipe back to home-feed and you will see it think that it’s not your turn.
  - the other bug here on this one is this double opening of the game. When I find the game is lagging in terms of being at the wrong place, I backswipe back. As seen in video, after the first backswipe I’m brought back to another version of the exact same game in the exact same place. Eventually I return back to homefeed where everything can eventually update and sync to the proper spot
- still wish there was easier way to see which games are your turn (grey out ones that aren’t, show all games that are your turn without having to click see all games)
- correspondence games on home feed should show how much time opponent has left before its game over (their perspective, not yours when it's their turn)
- once you play your move in your correspondence game it should automatically jump to your next available game or jump back to home feed if none are left
- on desktop, for the activity feed on your profile, correspondence games actually link to the game itself. App should do similarly

**Comment by veloce** [comment]
Should be fixed by https://github.com/lichess-org/mobile/commit/6a6baea0e9fdf1bc89bb3264bcec8b9dc82ddf71

**Comment by ijm8710** [comment]
> Should be fixed by https://github.com/lichess-org/mobile/commit/6a6baea0e9fdf1bc89bb3264bcec8b9dc82ddf71

Hey @veloce any chance to hear if any of the follow up items I commented on here were:

- also fixed
- not fixed but agree there should be open ticket to address later
- don't understand it (I have video on discord but can post them here-I'm the guy with the San Francisco 49ers logo on discord)
- don't agree to address at any point tbh

**Comment by veloce** [comment]
I don't understand your comment, sorry.

**Comment by ijm8710** [comment]
> I don't understand your comment, sorry.

Looks like you pushed a pull request to fix some correspondence issues mostly relating to the original poster which is good.

I had posted same on discord for a few months and glad you agreed there were some bugs there that were fixable.

But I also typed out above as the first reply in the thread, a few other comments relating to correspondence (6 in total).

Was curious if you agreed any of those also made sense for a pull request or if any needed more information to be provided.

**Comment by xdemiansmithx** [comment]
@veloce unfortunately I can still reproduce this on ios...

**Comment by xdemiansmithx** [comment]
@veloce this seems to have been fixed in a previous version but now there's a regression it seems (on iOS)

**Comment by veloce** [comment]
Can you tell me precisely in which version it was solved and in what version you saw first the regression? Thanks

**Comment by jas14** [comment]
I'm experiencing this with correspondence notifications on Android, app version 0.9.7. Specifically, the "it's your turn" notification brings me to the board state after my last move, where it's my opponent's turn. Let me know if I can clarify anything :)

**Comment by veloce** [comment]
Ok, I'm reopening to investigate this.

**Comment by ijm8710** [comment]
> Agree with this post and have shared the same. 
> 
> In addition to it not opening from right spot when clicking alert, there are several other bugs mostly relating to correspondence (should be able to video record any if needed): 
> 
> - recieve alert. But this time, instead of opening the alert, instead simply open the app. The feed should be automatically registering that it is now your turn, but it is failing to do so until the app is manually refreshed 
> - open alert (the game will actually register it is your turn this time), but instead of playing a move, backswipe back to home-feed and you will see it think that it’s not your turn.
>   - the other bug here on this one is this double opening of the game. When I find the game is lagging in terms of being at the wrong place, I backswipe back. After the first backswipe I’m brought back to another version of the exact same game in the exact same place. Eventually I return back to homefeed where everything can eventually update and sync to the proper spot
> - still wish there was easier way to see which games are your turn (grey out ones that aren’t, show all games that are your turn without having to click see all games)
> - correspondence games on home feed should show how much time opponent has left before its game over (their perspective, not yours when it's their turn)
> - once you play your move in your correspondence game it should automatically jump to your next available game or jump back to home feed if none are left
> - on desktop, for the activity feed on your profile, correspondence games actually link to the game itself. App should do similarly

@veloce most of these should be reproducible as well for correspondence games (plus a few extra comments)
